#!/usr/bin/env bash

set -e

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

cprintf() {
	case $1 in
		red)   printf "\e[31m" ;;
		green) printf "\e[32m" ;;
		blue)  printf "\e[34m" ;;
	esac

	printf "%b%b\n" "${@:2}" "\e[39m" >&2
}

main() {
	if ! command -v jq > /dev/null; then
		cprintf red "error: jq is required but not installed."
		return 1
	fi

	local conf=$XDG_CONFIG_HOME/spinner

	cprintf blue "Installing config..."
	mkdir -vp "$conf"
	cp -v spinners.json "$conf/spinners.json"

	local bin=/usr/local/bin

	cprintf blue "\nInstalling binary..."
	sudo cp -v spinner "$bin/spinner"
	sudo chmod -v u+x "$bin/spinner"

	cprintf green "\nInstallation complete!"
	printf 'run "spinner" to see available options\n'
}

main
