#!/usr/bin/env bash
#
# spinner: A command-line spinner
#
# Requirements: jq
#
# References:
# https://www.youtube.com/watch?v=muCcQ1W33tc
# https://github.com/bahamas10/ysap/blob/main/code/2026-01-07-spinner/spinner
# https://github.com/sindresorhus/cli-spinners
#
# Author:  Jesse Mirabel <sejjymvm@gmail.com>
# Date:    January 08, 2026
# License: MIT

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

DEF_CONFIG="$XDG_CONFIG_HOME/spinner/spinners.json"
DEF_STYLE="line"

DEBUG=false
CONFIG=
INTERVAL=
STYLE=

DEF_INTERVAL=
FRAMES=()
PID=

usage() {
	cat <<- EOF
		NAME
		  spinner - a command-line spinner

		SYNOPSIS
		  ${0##*/} [OPTIONS] <command> [args...]

		OPTIONS
		  -d             enable debug mode
		  -f <file>      set config file (default: ${DEF_CONFIG/$HOME/'~'})
		  -i <interval>  set frame interval in milliseconds
		  -l             list all spinner styles
		  -s <style>     set spinner style (default: $DEF_STYLE)
		  -h             show usage
	EOF
}

error() {
	{
		printf "\e[31m"
		printf "error: %b" "$*"
		printf "\e[39m\n"
	} >&2
}

debug() {
	if $DEBUG; then
		printf "[debug] %s\n" "$*" >&2
	fi
}

check_status() {
	case $? in
		0)     return 0 ;;
		1)     error "unknown spinner style" ;;
		2)     error "config file not found" ;;
		4 | 5) error "invalid JSON config file" ;;
		*)     error "unknown error" ;;
	esac
	exit 1
}

list_spinners() {
	local config=${CONFIG:-$DEF_CONFIG}

	debug "listing spinners"
	debug "config=$config"

	jq -re "keys[]" "$config" 2> /dev/null
	check_status

	debug "done"
}

load_spinner() {
	local style=${STYLE:-$DEF_STYLE}
	local config=${CONFIG:-$DEF_CONFIG}

	debug "loading spinner"
	debug "config=$config"
	debug "style=$style"

	DEF_INTERVAL=$(jq -re ".$style.interval" "$config" 2> /dev/null)
	check_status

	local line
	while IFS= read -r line; do
		FRAMES+=("$line")
	done < <(jq -re ".$style.frames[]" "$config" 2> /dev/null)
	check_status
}

start_spinner() {
	printf "\e[?25l" # make cursor invisible
	stty -echo       # turn off echoing

	local interval=${INTERVAL:-$DEF_INTERVAL}

	debug "interval=$interval(ms)"

	local s ms secs
	s=$((interval / 1000))
	ms=$((interval % 1000))
	secs=$s.$(printf "%03d" $ms)

	local frame
	while true; do
		for frame in "${FRAMES[@]}"; do
			printf "%s\r" "$frame"
			sleep "$secs"
		done
	done
}

stop_spinner() {
	printf "\e[?25h" # make cursor visible
	stty echo        # turn on echoing

	if [[ -n $PID ]]; then
		debug "killing process ($PID)"
		kill $PID
	fi

	debug "spinner stopped"
}

main() {
	if ! command -v jq > /dev/null; then
		error "jq is required but not installed"
		return 1
	fi

	if (($# == 0)); then
		usage >&2
		return 1
	fi

	local opt
	while getopts ":hdf:i:ls:" opt; do
		case $opt in
			h) usage; return 0 ;;
			d) DEBUG=true ;;
			f) CONFIG=$OPTARG ;;
			i) INTERVAL=$OPTARG ;;
			l) list_spinners; return 0 ;;
			s) STYLE=$OPTARG ;;
			:)
				error "-$OPTARG requires an argument"
				usage >&2
				return 1
				;;
			?)
				error "invalid option: -$OPTARG"
				usage >&2
				return 1
				;;
			*) usage >&2; return 1 ;;
		esac
	done
	shift $((OPTIND - 1))

	trap stop_spinner EXIT

	load_spinner

	debug "starting spinner"
	start_spinner &

	PID=$!
	debug "process ID (PID): $PID"

	"$@"
}

main "$@"
