#!/usr/bin/env bash
#
# spinner: A command-line spinner.
#
# Requirement: jq
#
# References:
# https://github.com/bahamas10/ysap/blob/main/code/2026-01-07-spinner/spinner
# https://www.youtube.com/watch?v=muCcQ1W33tc
# https://github.com/sindresorhus/cli-spinners
#
# Author:  Jesse Mirabel <sejjymvm@gmail.com>
# Date:    January 08, 2026
# License: MIT

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

DEF_CONFIG=$XDG_CONFIG_HOME/spinner/spinners.json
DEF_STYLE="line"

DEBUG=false
CONFIG=
INTV=
STYLE=

DEF_INTV=
FRAMES=()
SPINNER_PID=

usage() {
	cat <<- EOF
		NAME
		  spinner - a command-line spinner.

		SYNOPSIS
		  ${0##*/} [OPTIONS] <command> [args...]

		OPTIONS
		  -d             enable debug output
		  -f <file>      set JSON config file (default: ${DEF_CONFIG/$HOME/'~'})
		  -i <interval>  set frame interval in milliseconds
		  -l             list available spinners
		  -s <style>     set spinner style (default: $DEF_STYLE)
		  -h             show this help message
	EOF
}

error() {
	# red fg
	printf "\e[31m"
	printf "error: %b\n" "$*" >&2
	# reset fg
	printf "\e[39m"
}

debug() {
	if $DEBUG; then
		printf "[debug] %s\n" "$*" >&2
	fi
}

check_status() {
	case $? in
		0)     return 0 ;;
		1)     error "unknown spinner style" ;;
		2)     error "config file not found" ;;
		4 | 5) error "invalid JSON config file" ;;
		*)     error "unknown error" ;;
	esac
	exit 1
}

list_spinners() {
	local config=${CONFIG:-$DEF_CONFIG}

	debug "listing spinners"
	debug "config=$config"

	jq -re "keys[]" "$config" 2> /dev/null
	check_status

	debug "done"
}

load_spinner() {
	local style=${STYLE:-$DEF_STYLE}
	local config=${CONFIG:-$DEF_CONFIG}

	debug "loading spinner"
	debug "config=$config"
	debug "style=$style"

	DEF_INTV=$(jq -re ".$style.interval" "$config" 2> /dev/null)
	check_status

	local line
	while IFS= read -r line; do
		FRAMES+=("$line")
	done < <(jq -re ".$style.frames[]" "$config" 2> /dev/null)
	check_status
}

start_spinner() {
	local intv=${INTV:-$DEF_INTV}

	debug "interval=$intv(ms)"

	local s ms secs
	s=$((intv / 1000))
	ms=$((intv % 1000))
	secs=$s.$(printf "%03d" $ms)

	local frame
	while true; do
		for frame in "${FRAMES[@]}"; do
			printf "%s\r" "$frame"
			sleep "$secs"
		done
	done
}

stop_spinner() {
	# unhide cursor and re-enable echo
	printf "\e[?25h"
	stty echo

	if [[ -n $SPINNER_PID ]]; then
		debug "killing process ($SPINNER_PID)"
		kill $SPINNER_PID
	fi

	debug "spinner stopped"
}

main() {
	if ! command -v jq > /dev/null; then
		error "jq is required but not installed"
		return 1
	fi

	if (($# == 0)); then
		usage >&2
		return 1
	fi

	local opt
	while getopts ":hdf:i:ls:" opt; do
		case $opt in
			h) usage; return 0 ;;
			d) DEBUG=true ;;
			f) CONFIG=$OPTARG ;;
			i) INTV=$OPTARG ;;
			l) list_spinners; return 0 ;;
			s) STYLE=$OPTARG ;;
			:)
				error "-$OPTARG requires an argument"
				usage >&2
				return 1
				;;
			?)
				error "invalid option: -$OPTARG"
				usage >&2
				return 1
				;;
			*) usage >&2; return 1 ;;
		esac
	done
	shift $((OPTIND - 1))

	trap stop_spinner EXIT

	# hide cursor and disable echo
	printf "\e[?25l"
	stty -echo

	load_spinner

	debug "starting spinner"
	start_spinner &

	SPINNER_PID=$!
	debug "process ID (PID): $SPINNER_PID"

	"$@"
}

main "$@"
