#!/usr/bin/env bash
#
# spinner: Run a command with an animated spinner.
#
# Requires `jq` to extract spinners from a JSON config file.
#
# References:
# https://github.com/bahamas10/ysap/blob/main/code/2026-01-07-spinner/spinner
# https://www.youtube.com/watch?v=muCcQ1W33tc
# https://github.com/sindresorhus/cli-spinners
#
# Author:  Jesse Mirabel <sejjymvm@gmail.com>
# Date:    January 08, 2026
# License: MIT

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
DEFAULT_JSON=$XDG_CONFIG_HOME/spinner/spinners.json
DEFAULT_STYLE="line"
DEBUG=false

FRAMES=()
INTERVAL=
SPINNER_PID=

usage() {
	cat <<- EOF
		USAGE: ${0##*/} [OPTIONS] <command> [args...]

		Run a command with an animated spinner.

		OPTIONS:
		  -d            enable debug output
		  -f <file>     set JSON config file (default: ${DEFAULT_JSON/$HOME/'~'})
		  -l            list available spinners
		  -s <style>    set spinner style (default: $DEFAULT_STYLE)
		  -h            show this help message
	EOF
}

error() {
	# red fg
	printf "\e[31m"
	printf "error: %b\n" "$*" >&2
	# reset fg
	printf "\e[39m"
}

debug() {
	if $DEBUG; then
		printf "[debug] %s\n" "$*" >&2
	fi
}

check_status() {
	case $? in
		0)     return 0 ;;
		1 | 5) error "unknown spinner" ;;
		2)     error "config file not found" ;;
		4)     error "invalid JSON config file" ;;
		*)     error "unknown error" ;;
	esac
	exit 1
}

list_spinners() {
	local file=${1:-$DEFAULT_JSON}

	debug "listing spinners from $file"

	jq -re "keys[]" "$file" 2> /dev/null
	check_status
}

load_spinner() {
	local style=${1:-$DEFAULT_STYLE}
	local file=${2:-$DEFAULT_JSON}

	INTERVAL=$(jq -re ".$style.interval" "$file" 2> /dev/null)
	check_status

	local line
	while IFS= read -r line; do
		FRAMES+=("$line")
	done < <(jq -re ".$style.frames[]" "$file" 2> /dev/null)
	check_status
}

start_spinner() {
	local s ms secs
	s=$((INTERVAL / 1000))
	ms=$((INTERVAL % 1000))
	secs=$s.$(printf "%03d" $ms)

	debug "frame interval: ${INTERVAL}ms (${secs}s)"

	local frame
	while true; do
		for frame in "${FRAMES[@]}"; do
			printf "%s\r" "$frame"
			sleep "$secs"
		done
	done
}

stop_spinner() {
	# unhide cursor and re-enable echo
	printf "\e[?25h"
	stty echo

	if [[ -n $SPINNER_PID ]]; then
		debug "killing spinner ($SPINNER_PID)"
		kill $SPINNER_PID
	fi

	debug "spinner stopped"
}

main() {
	if ! command -v jq > /dev/null; then
		error "jq is required but not installed"
		return 1
	fi

	if (($# == 0)); then
		usage >&2
		return 1
	fi

	local opt file style
	while getopts ":hdf:ls:" opt; do
		case $opt in
			h) usage; return 0 ;;
			d) DEBUG=true ;;
			f) file=$OPTARG ;;
			l) list_spinners "$file"; return 0 ;;
			s) style=$OPTARG ;;
			:)
				error "-$OPTARG requires an argument"
				usage >&2
				return 1
				;;
			?)
				error "invalid option: -$OPTARG"
				usage >&2
				return 1
				;;
			*) usage >&2; return 1 ;;
		esac
	done
	shift $((OPTIND - 1))

	file=${file:-$DEFAULT_JSON}
	style=${style:-$DEFAULT_STYLE}

	trap stop_spinner EXIT

	# hide cursor and disable echo
	printf "\e[?25l"
	stty -echo

	debug "loading $style spinner from $file"
	load_spinner "$style" "$file"

	debug "starting spinner"
	start_spinner &

	SPINNER_PID=$!
	debug "spinner PID: $SPINNER_PID"

	"$@"
}

main "$@"
