#!/usr/bin/env bash

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

log() {
	case $1 in
		success) printf "\e[32m" ;;
		info)    printf "\e[34m" ;;
	esac

	printf "%b%b\n" "${@:2}" "\e[39m" >&2
}

main() {
	log info "Removing config..."
	rm -vr "$XDG_CONFIG_HOME/spinner"

	log info "\nRemoving binary..."
	sudo rm -v "/usr/bin/spinner"

	log success "\nUninstallation complete!"
}

main
