#!/usr/bin/env bash

FG_GREEN="\e[32m"
FG_BLUE="\e[34m"
FG_RESET="\e[39m"

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

main() {
	printf "%bRemoving config...%b\n" "$FG_BLUE" "$FG_RESET"
	rm -vr "$XDG_CONFIG_HOME/spinner"

	printf "\n%bRemoving binary...%b\n" "$FG_BLUE" "$FG_RESET"
	sudo rm -v "/usr/local/bin/spinner"

	printf "\n%bUninstallation complete!%b\n" "$FG_GREEN" "$FG_RESET"
}

main
