#!/usr/bin/env bash

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

cprintf() {
	case $1 in
		g) printf "\e[32m" ;;
		b) printf "\e[34m" ;;
	esac
	printf "%b\n" "${@:2}" >&2
	printf "\e[39m"
}

main() {
	cprintf b "Removing config..."
	rm -vr "$XDG_CONFIG_HOME/spinner"

	cprintf b "\nRemoving binary..."
	sudo rm -v "/usr/local/bin/spinner"

	cprintf g "\nUninstallation complete!"
}

main
